package com.nefedov.nexigntestapplication.dto;

import com.nefedov.nexigntestapplication.utils.TaskStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;

@Builder
@Data
@Schema(description = "Task response model")
public class TaskResponseModel {

    @Schema(description = "Task autogenerated id", example = "3")
    private long id;

    @Schema(description = "Task name", example = "Reading")
    private String name;

    @Schema(description = "Task duration in seconds", example = "15")
    private int duration;

    @Schema(description = "Current task status")
    private TaskStatus status;

    @Schema(description = "Task creation date and time")
    private LocalDateTime createdDate;
}
